export const verificationRequests = [
  {
    docType: "Passport",
    user: "Emma Thompson",
    date: "2023-12-01",
    anomalyScore: "92%",
    crossDocMatching: "No",
    mismatchedFields: [
      { field: "Date of Birth", doc1Value: "1990-05-15", doc2Value: "1990-05-16" },
    ],
    docId: "PP-2023-001",
    institution: "Department of Foreign Affairs",
    priority: "high",
    status: "pending",
    history: ["Submitted for review", "Cross document mismatch detected"],
    document1: { name: "Emma Thompson", dob: "1990-05-15", nationality: "British", passportNumber: "GBR123456" },
    document2: { name: "Emma Thompson", dob: "1990-05-16", nationality: "British", passportNumber: "GBR123456" },
  },
  {
    docType: "Driver's License",
    user: "Michael Chen",
    date: "2023-11-28",
    anomalyScore: "45%",
    crossDocMatching: "Yes",
    mismatchedFields: [],
    docId: "DL-2023-089",
    institution: "Department of Motor Vehicles",
    priority: "medium",
    status: "review",
    history: ["Submitted for review", "Anomaly detected in signature"],
    document1: { name: "Michael Chen", dob: "1988-09-22", licenseNumber: "DL78901234", expiryDate: "2028-09-22" },
    document2: { name: "Michael Chen", dob: "1988-09-22", licenseNumber: "DL78901234", expiryDate: "2028-09-22" },
  },
  {
    docType: "Marriage Certificate",
    user: "Sophia Rodriguez",
    date: "2023-12-05",
    anomalyScore: "12%",
    crossDocMatching: "Yes",
    mismatchedFields: [],
    docId: "MC-2023-567",
    institution: "City Hall",
    priority: "low",
    status: "approved",
    history: ["Submitted for review", "Approved"],
    document1: { spouse1: "Sophia Rodriguez", spouse2: "Daniel Lee", dateOfMarriage: "2023-11-15", certificateNumber: "MC123456" },
    document2: { spouse1: "Sophia Rodriguez", spouse2: "Daniel Lee", dateOfMarriage: "2023-11-15", certificateNumber: "MC123456" },
  },
  {
    docType: "University Degree",
    user: "Alexander Johnson",
    date: "2023-12-03",
    anomalyScore: "78%",
    crossDocMatching: "No",
    mismatchedFields: [
      { field: "Graduation Date", doc1Value: "2022-06-15", doc2Value: "2022-07-15" },
    ],
    docId: "UD-2023-234",
    institution: "Stanford University",
    priority: "high",
    status: "pending",
    history: ["Submitted for review", "Cross document mismatch detected"],
    document1: { name: "Alexander Johnson", degree: "Bachelor of Science", major: "Computer Science", graduationDate: "2022-06-15" },
    document2: { name: "Alexander Johnson", degree: "Bachelor of Science", major: "Computer Science", graduationDate: "2022-07-15" },
  },
  {
    docType: "Birth Certificate",
    user: "Olivia Brown",
    date: "2023-11-30",
    anomalyScore: "5%",
    crossDocMatching: "Yes",
    mismatchedFields: [],
    docId: "BC-2023-789",
    institution: "National Registry",
    priority: "low",
    status: "approved",
    history: ["Submitted for review", "Approved"],
    document1: { name: "Olivia Brown", dateOfBirth: "2023-11-10", placeOfBirth: "London", parentNames: "Emily and James Brown" },
    document2: { name: "Olivia Brown", dateOfBirth: "2023-11-10", placeOfBirth: "London", parentNames: "Emily and James Brown" },
  },
];

